server:
  port: 80

spring:
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:~/data/server;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 100MB
sonacube-token: 973b4298793d432aeccb2236f6f46301944d90c8


